name: Actions Runner Controller Demo
on:
  push:
    branches: [main]

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
      - name: Setup node and npm path
        run: |
          export PATH="/home/runner/externals/node20/bin:$PATH"
      - run: node -v